#!/usr/bin/env bash
# Script to install and configure HAproxy on lb-01 server

# Install HAproxy
sudo apt update -y
sudo apt-get install -y haproxy

# Configure HAproxy
ws1="server 228023-web-01 54.166.147.155:80 check"
ws2="server 228023-web-02 54.237.127.172:80 check"
frontend="\nfrontend haproxy-main\n\tbind *:80\n\tdefault_backend webservers"
backend="\nbackend webservers\n\tbalance roundrobin\n\t$ws1\n\t$ws2"

sudo sed -i "$ a\\$frontend" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\\$backend" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ENABLED=1" /etc/default/haproxy

# Enable HAproxy on boot
sudo systemctl enable haproxy

# Start HAproxy
sudo service haproxy start

# Reload HAproxy
sudo service haproxy reload
