#!/usr/bin/env bash
# Script to install and configure HAproxy on lb-01 server
sudo apt update

# Install HAproxy 2.8
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt update
sudo apt-get install -y haproxy=2.8.\*

# Configure HAproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
config_file="/etc/haproxy/haproxy.cfg"
ws1="server 228023-web-01 54.166.147.155:80 check"
ws2="server 228023-web-02 54.237.127.172:80 check"
frontend="\nfrontend haproxy-main\n\tbind *:80\n\tdefault_backend webservers"
backend="\nbackend webservers\n\tbalance roundrobin\n\t$ws1\n\t$ws2"
sudo sed -i "$ a\\$frontend" "$config_file"
sudo sed -i "$ a\\$backend" "$config_file"

# Restart service
sudo service haproxy restart 2>&1
