#!/usr/bin/env bash
# A Bash script that configures a server to listen on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
