#!/usr/bin/env bash
# Creates PID file

# Handle SIGTERM
sigterm_handler() {
	echo "I hate the kill command"
}

# Handle SIGINT
sigint_handler() {
	echo "Y U no love me ?!"
}

# Handle SIGQUIT or SIGTERM
sigquit_handler() {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}

# Signal handlers
trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_handler' SIGQUIT SIGTERM

# Create file
echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 1
done
