#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
# Handles loginc for SIGTERM signal

trap "handle_sigterm" SIGTERM

handle_sigterm() {
	echo "I am invincible!!!"
}

while true
do
	echo "To infinity and beyond"
done
