#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes:
#+ displays hours from 0 to 12
#+ displays minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
	minute=1
	echo "Hour: $hour"

	while [ $minute -lt 60 ]
	do
		echo "$minute"
		(( minute++ ))
	done

	(( hour++ ))
done
