#!/usr/bin/env bash
# A script that displays:
#+ the content of the current directory
#+ in a list format
#+ where only the part of the name after the first dash is displayed

DIR_LIST="$(ls)"
for file in $DIR_LIST
do
	file=${file#*-}
	echo "$file"
done
