#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user

# Allow user nginx to run Nginx
sudo chmod 644 /etc/nginx/nginx.conf

# Run as the nginx user
sudo -u nginx nginx

# Create an Nginx server block to listen on all active IPs on port 8080
cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 8080 default_server;
	listen [::]:8080 default_server;
	root /var/www/html;
	index index.html index.htm;
}
EOF

# Reload Nginx to apply the changes
nginx -s reload
