#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user

# Ensure nginx is installed
if ! command -v nginx &> /dev/null;
then
	sudo apt update
	sudo apt install -y nginx
fi

# Run as nginx user
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Configure port 8080
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo nginx -s reload
