#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user
pkill apache2
chmod 644 /etc/nginx/nginx.conf
chown -R nginx /etc/nginx/nginx.conf
sudo -u nginx -c "sed -i -e '/s/80/8080/g' /etc/nginx/sites-available/default"
sudo -u nginx -c "service nginx restart" 2&> /dev/null
